// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDvIaGwbvA0uN46BCd48yTFlycxQMw67g',
    appId: '1:188082831731:web:b21773a4620e0870a44506',
    messagingSenderId: '188082831731',
    projectId: 'e-commers-sneakers-app',
    authDomain: 'e-commers-sneakers-app.firebaseapp.com',
    storageBucket: 'e-commers-sneakers-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL58n3Tu36rUdAi7OXGuVrGLC1opiElig',
    appId: '1:188082831731:android:cd6f55547996ce7aa44506',
    messagingSenderId: '188082831731',
    projectId: 'e-commers-sneakers-app',
    storageBucket: 'e-commers-sneakers-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiAwEOCV3FfksLTmHO7lvxowQ4qYjcbuM',
    appId: '1:188082831731:ios:872198c10eaf2ad1a44506',
    messagingSenderId: '188082831731',
    projectId: 'e-commers-sneakers-app',
    storageBucket: 'e-commers-sneakers-app.appspot.com',
    iosBundleId: 'com.example.eCommersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiAwEOCV3FfksLTmHO7lvxowQ4qYjcbuM',
    appId: '1:188082831731:ios:872198c10eaf2ad1a44506',
    messagingSenderId: '188082831731',
    projectId: 'e-commers-sneakers-app',
    storageBucket: 'e-commers-sneakers-app.appspot.com',
    iosBundleId: 'com.example.eCommersApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDvIaGwbvA0uN46BCd48yTFlycxQMw67g',
    appId: '1:188082831731:web:359c4b59490a8ac4a44506',
    messagingSenderId: '188082831731',
    projectId: 'e-commers-sneakers-app',
    authDomain: 'e-commers-sneakers-app.firebaseapp.com',
    storageBucket: 'e-commers-sneakers-app.appspot.com',
  );
}
